---

#########
# NOTES #
#########

# This config file runs a feature search pipeline
# using Sequential Forward Floating Selection
# on the P186 3A Only dataset.

##########
# CONFIG #
##########

RUN_NAME: p186_3A_Only
# For today's date: auto
# To load or update a previous run: YYYYMMDD
RUN_DATE: auto

##############
# FILE PATHS #
##############

MAIN: ../data/20190904_p186_3A_Only.csv
# If no test set: False
TEST: False

#################
# DATA SETTINGS #
#################

TARGET: Group
TEST: False
META_COLS:
  - Subject

CLASSES:
  - 1
  - 2

#####################
# PIPELINE SETTINGS #
#####################

ESTIMATOR:
  CODE: LR
  
K_FEATURES: 3

CORRELATION_FILTER:
  USE: Y
  THRESHHOLD: .90
  
MUTUAL_INFO_FILTER:
  USE: Y
  NO_FEATURES: 10

...
